---
resources:
  - ../base
namespace: deployment-agnostic-3
commonLabels:
  app: deployment-agnostic-3
patches:
  # Customize path to application.
  - target:
      kind: Subscription
      name: subscription
    patch: |-
      - op: replace
        path: /metadata/annotations/apps.open-cluster-management.io~1github-path
        value: workloads/deployment/odr-regional-agnostic
      - op: replace
        path: /metadata/annotations/apps.open-cluster-management.io~1github-branch
        value: use-agnostic-global-with-multi-wl
