---
apiVersion: ramendr.openshift.io/v1alpha1
kind: DRPlacementControl
metadata:
  name: drpc
spec:
  preferredCluster: perf2
  drPolicyRef:
    name: perf2-perf3-5m
  placementRef:
    kind: Placement
    name: placement
  pvcSelector:
    matchLabels:
      appname: busybox
