---
apiVersion: ramendr.openshift.io/v1alpha1
kind: DRPlacementControl
metadata:
  name: drpc
spec:
  preferredCluster: hyper6
  drPolicyRef:
    name: hyper6-hyper7-5m
  placementRef:
    kind: Placement
    name: placement
  pvcSelector:
    matchLabels:
      appname: busybox
