---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      appname: busybox
  template:
    metadata:
      labels:
        appname: busybox
    spec:
      containers:
        - name: logger
          image: quay.io/nirsof/busybox:stable
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - |
              emit() {
                  echo "$(date) $1" | dd of=/dev/xvda bs=512 seek=$offset count=1 conv=notrunc; offset=$((offset + 1));
                  sync
              }
              trap "emit STOP; exit" TERM
              emit START
              while true; do
                  sleep 10 & wait
                  emit UPDATE
              done
          volumeDevices:
            - name: datelog
              devicePath: /dev/xvda
      volumes:
        - name: datelog
          persistentVolumeClaim:
            claimName: busybox-pvc
