---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: busybox-cg2-pvc2
spec:
  accessModes:
    - ReadWriteMany
  # Customize in your overlay.
  storageClassName: ocs-storagecluster-cephfs
  resources:
    requests:
      storage: 1Gi
