---
resources:
  - ../../base
namespace: deploy-cg-2pods-10pvcs
commonLabels:
  app: deploy-cg-2pods-10pvcs
patches:
  # Customize path to application.
  - target:
      kind: DRPlacementControl
      name: drpc
    patch: |-
      - op: replace
        path:  /metadata/annotations/drplacementcontrol.ramendr.openshift.io~1is-cg-enabled
        value: true
      - op: replace
        path: /spec/preferredCluster
        value: hyper3
      - op: replace
        path: /spec/drPolicyRef/name
        value: hyper3-hyper4-5m
      - op: replace
        path: /metadata/name
        value: drpc-2pods-10pvcs
