---
resources:
  - ../../base
namespace: deployment-cg-cephfs
commonLabels:
  app: deployment-cg-cephfs
patches:
  # Customize path to application.
  - target:
      kind: DRPlacementControl
      name: drpc
    patch: |-
      - op: replace
        path:  /metadata/annotations/drplacementcontrol.ramendr.openshift.io~1is-cg-enabled
        value: true
      - op: replace
        path: /spec/preferredCluster
        value: hyper6
      - op: replace
        path: /spec/drPolicyRef/name
        value: hyper6-hyper7-5m
      - op: replace
        path: /metadata/name
        value: busybox-with-cg
