---
resources:
  - ../../base/cg-rbd
patches:
  # Customize for internal cephfs storage.
  - target:
      kind: PersistentVolumeClaim
      name: busybox-cg2-pvc1
    patch: |-
      - op: replace
        path: /spec/storageClassName
        value: ocs-storagecluster-ceph-rbd
      - op: replace
        path: /spec/accessModes
        value:
          - ReadWriteOnce
  - target:
      kind: PersistentVolumeClaim
      name: busybox-cg2-pvc2
    patch: |-
      - op: replace
        path: /spec/storageClassName
        value: ocs-storagecluster-ceph-rbd
      - op: replace
        path: /spec/accessModes
        value:
          - ReadWriteOnce