---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: busybox-gitops
  namespace: busybox-sample
spec:
  type: GitHub
  pathname: https://github.com/BenamarMK/ocm-ramen-samples.git
