---
apiVersion: ramendr.openshift.io/v1alpha1
kind: DRPlacementControl
metadata:
  labels:
    app: busybox-sample
  name: drpc-for-volsync-test
spec:
  drPolicyRef:
    name: ocp4perf1-ocp4perf2-2m
  placementRef:
    kind: PlacementRule
    name: busybox-placement
  preferredCluster: ocp4perf1
  failoverCluster: ocp4perf2
  pvcSelector:
    matchLabels:
      appname: busybox
