---
apiVersion: ramendr.openshift.io/v1alpha1
kind: DRPlacementControl
metadata:
  labels:
    app: busybox-sample
  name: busybox-drpc
spec:
  drPolicyRef:
    name: odr-policy-east-west-rpo-5m
  placementRef:
    kind: PlacementRule
    name: busybox-placement
  preferredCluster: prsurve-vm-d
  failoverCluster: vmware-dccp-one
  pvcSelector:
    matchLabels:
      appname: busybox
