---
apiVersion: ramendr.openshift.io/v1alpha1
kind: DRPlacementControl
metadata:
  name: busybox-drpc
  labels:
    app: benamar-ns
spec:
  preferredCluster: "cluster1"
  drPolicyRef:
    name: cluster1-cluster2-5m
  placementRef:
    kind: PlacementRule
    name: busybox-placement
  pvcSelector:
    matchLabels:
      appname: busybox
