---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/reconcile-option: mergeAndOwn
    apps.open-cluster-management.io/github-branch: scale-up-pods-and-pvcs-to-10-each
    apps.open-cluster-management.io/github-path: busybox
  labels:
    app: busybox-sample
  name: busybox-sub
spec:
    channel: ramen-samples/ramen-gitops
    placement:
      placementRef:
        kind: PlacementRule
        name: busybox-placement
