---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    appname: busybox
    ramendr.openshift.io/consistency-group: cg-for-lab2
  name: busybox-cg2-pvc1
spec:
  accessModes:
    - ReadWriteOnce
  # Customize in your overlay.
  storageClassName: ocs-storagecluster-cephfs
  resources:
    requests:
      storage: 1Gi
