---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: busybox-another-pvc
spec:
  accessModes:
    - ReadWriteOnce
  # Customize in your overlay.
  storageClassName: ocs-storagecluster-cephfs
  resources:
    requests:
      storage: 1Gi
