---
commonLabels:
  appname: busybox
resources:
  - ../base
  - addtional-pvc.yaml
  - pvc-in-cg.yaml
patchesStrategicMerge:
  - deployment.yaml
patches:
  # Customize for internal cephfs storage.
  - target:
      kind: PersistentVolumeClaim
      name: busybox-pvc
    patch: |-
      - op: replace
        path: /spec/storageClassName
        value: rook-cephfs
      - op: replace
        path: /spec/accessModes
        value:
          - ReadWriteMany
