---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: busybox-cg-pvc1
  labels:
    cg: test
spec:
  accessModes:
    - ReadWriteOnce
  # Customize in your overlay.
  storageClassName: rook-cephfs
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: busybox-cg-pvc2
  labels:
    cg: test
spec:
  accessModes:
    - ReadWriteOnce
  # Customize in your overlay.
  storageClassName: rook-cephfs
  resources:
    requests:
      storage: 1Gi