---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: busybox-cg-pvc1
spec:
  accessModes:
    - ReadWriteOnce
  # Customize in your overlay.
  storageClassName: ocs-storagecluster-cephfs
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: busybox-cg-pvc2
spec:
  accessModes:
    - ReadWriteOnce
  # Customize in your overlay.
  storageClassName: ocs-storagecluster-cephfs
  resources:
    requests:
      storage: 1Gi