---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: busybox-cg1-pvc1
  labels:
    "ramendr.openshift.io/consistency-group": "cg1"
spec:
  accessModes:
    - ReadWriteOnce
  # Customize in your overlay.
  storageClassName: rook-cephfs
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: busybox-cg1-pvc2
  labels:
    "ramendr.openshift.io/consistency-group": "cg1"
spec:
  accessModes:
    - ReadWriteOnce
  # Customize in your overlay.
  storageClassName: rook-cephfs
  resources:
    requests:
      storage: 1Gi