---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: busybox-pvc
  namespace: busybox-sample
  labels:
    appname: busybox
spec:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: "gp2-ramen-test-bug"
  resources:
    requests:
      storage: 2Gi
