---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: busybox-pvc-3
  labels:
    appname: busybox
spec:
  accessModes: [ "ReadWriteOnce" ]
  #storageClassName: "rook-ceph-block"
  storageClassName: "gp2-csi"
  resources:
    requests:
      storage: 1Gi
