---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: busybox-cg1-pvc1
spec:
  accessModes:
    - ReadWriteMany
  # Customize in your overlay.
  storageClassName: ocs-storagecluster-cephfs
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: busybox-cg1-pvc2
spec:
  accessModes:
    - ReadWriteMany
  # Customize in your overlay.
  storageClassName: ocs-storagecluster-cephfs
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: busybox-cg2-pvc1
spec:
  accessModes:
    - ReadWriteOnce
  # Customize in your overlay.
  storageClassName: ocs-storagecluster-ceph-rbd
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: busybox-cg2-pvc2
spec:
  accessModes:
    - ReadWriteOnce
  # Customize in your overlay.
  storageClassName: ocs-storagecluster-ceph-rbd
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: busybox-cg3-pvc1
spec:
  volumeMode: Block
  accessModes:
    - ReadWriteOnce
  # Customize in your overlay.
  storageClassName: ocs-storagecluster-ceph-rbd
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: busybox-cg3-pvc2
spec:
  volumeMode: Block
  accessModes:
    - ReadWriteOnce
  # Customize in your overlay.
  storageClassName: ocs-storagecluster-ceph-rbd
  resources:
    requests:
      storage: 1Gi