---
resources:
  - ../../base
namespace: deploy-cg-2pods-10pvcs
commonLabels:
  app: deploy-cg-2pods-10pvcs
patches:
  # Customize path to application.
  - target:
      kind: Subscription
      name: subscription
    patch: |-
      - op: replace
        path: /metadata/annotations/apps.open-cluster-management.io~1github-path
        value: workloads/deployment/odr-regional-cephfs/cg
      - op: replace
        path: /metadata/annotations/apps.open-cluster-management.io~1github-branch
        value: cg-cephfs-2pods-10pvcs
