---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: busybox-cg2-pvc1
spec:
  accessModes:
    - ReadWriteMany
  # Customize in your overlay.
  storageClassName: rook-cephfs1
  resources:
    requests:
      storage: 1Gi
