---
commonLabels:
  appname: busybox
resources:
  - ../base
  - pvc-in-cg.yaml
patchesStrategicMerge:
  - deployment.yaml
patches:
  # Customize for internal ceph rbd storage.
  - target:
      kind: PersistentVolumeClaim
      name: busybox-pvc
    patch: |-
      - op: replace
        path: /spec/storageClassName
        value: rook-ceph-block
